---
title: "Experiment of CL-Eigenwords"
date: "`r Sys.time()`"
output: html_document
---

```{r, include = FALSE}
time.begin <- Sys.time()

source("./../../src/kadingir.R", chdir = TRUE)
```

# Execute CL-Eigenwords
```{r}
languages <- "en bg cs da de el es et fi fr hu it lt lv nl pl pt ro sk sl sv"
languages <- strsplit(languages, " ")[[1]]

paths.corpus <- list()
for(lang in languages){
  paths.corpus[[lang]] <- list(parallel=paste0("./../../corpora/europarl/europarl-v7.merged.", lang, ".tokenized.100000"))
}

r <- CLEigenwords(paths.corpus,
                  sizes.vocabulary = rep(1000, length(languages)),
                  dim.common = 40, dim.evd = 80,
                  sizes.window = rep(2, length(languages)),
                  aliases.languages=languages,
                  plot = TRUE,
                  link_v_c = FALSE,
                  weight.vsdoc = rep(1.0, length(languages)))

save(r, file = "res_cleigenwords.Rdata")
```


```{r}
p <- r$p_head_domains
print(p)

V <- matrix(0, nrow = 0, ncol = ncol(r$V))
vocab.words <- c()
for(i in seq(languages)){
  lang <- languages[i]
  
  V <- rbind(V, r$V[(p[2*i - 1] + (i!=1)):p[2*i], ])
  vocab.words <- c(vocab.words, paste0("(", lang, ")", r$vocab.words[[i]]))
}
```

## Example of vector representation
```{r}
row.sample <- c(p[1], p[2:9]+1)
r$V[row.sample, 1:20]
```

## biplot
```{r}
queries <- c(paste0("(en)", c("i", "you", "he", "she", "my", "your", "her", "we")),
             paste0("(es)", c("yo", "tu", "él", "ella", "mi", "su", "nosotros")),
             paste0("(de)", c("ich", "du", "er", "sie", "mein", "ihr", "sie", "wir")),
             paste0("(fr)", c("je", "tu", "il", "elle", "mon", "votre", "son", "nous")))
n.queries <- length(queries)

print(queries[queries %in% vocab.words])

VV <- V
row.names(VV) <- vocab.words
pr.v2 <- prcomp(VV[queries[queries %in% vocab.words],])
plot(pr.v2$x[ , 1:2], pch = 1, col = "grey")
text(pr.v2$x[ , 1], pr.v2$x[ , 2], row.names(pr.v2$x))
```


```{r}
n.queries.eachlang <- 100
index.eachlang <- 1:100 + 20
n.languages <- length(languages)
index.queries <- rep((seq(n.languages) - 1) * 1000, each=n.queries.eachlang) + rep(index.eachlang, n.languages)
queries <- vocab.words[index.queries]

VV <- V
row.names(VV) <- vocab.words
vectors <- VV[queries[queries %in% vocab.words], ]
pr.v2 <- prcomp(vectors)
plot(pr.v2$x[ , 1:2], pch = 1, col = "grey", xlim=c(-0.001, 0.000), ylim=c(-0.001, 0.001))
text(pr.v2$x[ , 1], pr.v2$x[ , 2], row.names(pr.v2$x), cex = 0.7)
```

```{r, eval=FALSE}
library(tsne)

vectors.tsne <- tsne(vectors, max_iter=200)
vectors.tsne2 <- vectors.tsne + matrix(rnorm(2*nrow(vectors)), ncol=2)
cairo_pdf(file = "tsne_words.pdf", width = 60, height = 40, family = "Sans")
plot(vectors.tsne, t='n', main="tsne")
text(vectors.tsne2, labels=queries)
dev.off()
```

# Example of lexical translation task
(en)I = (es)yo

```{r}
MostSimilar(V, vocab.words, positive=c("(en)we"), distance = "cosine")
MostSimilar(V, vocab.words, positive=c("(es)yo"), distance = "cosine")
MostSimilar(V, vocab.words, positive=c("(en)france"), distance = "cosine")
MostSimilar(V, vocab.words, positive=c("(en)him", "(es)yo"), negative=c("(en)he"), distance = "cosine")
```

# Execute some (monolingual) tasks for vector representation of english words
```{r, eval=FALSE}
V.en <- r$V[(p[7]+1):p[8], ]
vocab.en <- r$vocab.words[[4]]

TestGoogleTasks(V.en, vocab.en, n.cores = 12)
TestWordsim353(V.en, vocab.en)
```

# Run time
```{r}
Sys.time() - time.begin
Sys.time()
```