---
title: "Run cleigenwords with monolingual corpus"
date: "`r Sys.time()`"
output: html_document
---

```{r}
time.begin <- Sys.time()

source("./../../src/kadingir.R", chdir = TRUE)
```

```{r}
paths.corpus <- list(en = list(parallel    = "./../../corpora/europarl/europarl-v7.es-en.en.tokenized.10000",
                               monolingual = "./../../corpora/europarl/europarl-v7.es-en.en.tokenized.10000"))

res.cleigenwords <- CLEigenwords(paths.corpus, sizes.vocabulary=c(1000), dim.common=50, dim.evd=110,
                                 sizes.window = c(2), aliases.languages=c("en"), plot = TRUE,
                                 weight.vsdoc = c(1.0))

save(res.cleigenwords, file = "res_cleigenwords_monolingual.Rdata")
```

```{r}
pp <- res.cleigenwords$p_head_domains
V.en <- res.cleigenwords$V[(pp[1]+1):pp[2], ]
vocab.sizes <- res.cleigenwords$vocab.sizes
vocab.words.en <- res.cleigenwords$vocab.words[[1]]
```

```{r}
MostSimilar(V.en, vocab.words.en, positive=c("he"), distance = "cosine")
MostSimilar(V.en, vocab.words.en, positive=c("woman"), distance = "cosine")
TestGoogleTasks(V.en, vocab.words.en, n.cores = 10)
TestWordsim353(V.en, vocab.words.en)
```

```{r}
Sys.time() - time.begin
Sys.time()
```