---
title: "Eigenwordsの実験"
output: html_document
---

```{r, include=FALSE}
set.seed(0)

source("./../kadingir.R", chdir=TRUE)


## Tuning parameters
n.vocabulary <- 100000 # 語彙に含める単語数
dim.internal <- 200   # 共通空間の次元
window.size <- 2      # 前後何個の単語をcontextとするか
mode <- "oscca"
path.corpus <- "./../data/reuters/reuters_rcv1_text.csv"
#path.corpus <- "./../data/text8"
```


```{r}
res.eigenwords <- Eigenwords(path.corpus, n.vocabulary, dim.internal, window.size, mode = mode)
save(res.eigenwords, file = "res_eigenwords.Rdata")
```

# Check vector representation
```{r}
MostSimilar(res.eigenwords$svd$word_vector, res.eigenwords$vocab.words,
            positive=c("man"), distance = "cosine")
```

```{r}
MostSimilar(res.eigenwords$svd$word_vector, res.eigenwords$vocab.words,
            positive=c("king", "woman"), negative=c("man"), distance = "cosine")
```


# Test some tasks for check
```{r}
TestGoogleTasks(res.eigenwords$svd$word_vector, res.eigenwords$vocab.words, n.cores = 24)
```

```{r}
TestWordsim353(res.eigenwords$svd$word_vector, res.eigenwords$vocab.words)
```