---
title: "Experiment of CL-Eigenwords"
date: "`r Sys.time()`"
output: html_document
---

```{r, include = FALSE}
time.begin <- Sys.time()

source("./../src/kadingir.R", chdir = TRUE)
source("./../src/cleigenwords.R", chdir = TRUE)
```

# Execute CL-Eigenwords
```{r}
paths.corpus <- list(es = list(parallel    = "./../corpora/europarl/europarl-v7.merged.es.tokenized"),
                     de = list(parallel    = "./../corpora/europarl/europarl-v7.merged.de.tokenized"),
                     fr = list(parallel    = "./../corpora/europarl/europarl-v7.merged.fr.tokenized"),
                     en = list(parallel    = "./../corpora/europarl/europarl-v7.merged.en.tokenized"))

r <- CLEigenwords(paths.corpus,
                  sizes.vocabulary = c(50000, 50000, 50000, 50000),
                  dim.common = 200,
                  sizes.window = c(2, 2, 2, 2),
                  aliases.languages=c("es", "de", "fr", "en"),
                  plot = TRUE,
                  weighting_tf = FALSE,
                  link_v_c = FALSE,
                  weight.vsdoc = c(1.0, 1.0, 1.0, 1.0))

save(r, file = "res_cleigenwords.Rdata")
```


```{r}
p <- r$p_head_domains
print(p)

V1 <- r$V[p[1]:p[2], ]
V2 <- r$V[(p[3]+1):p[4], ]
V3 <- r$V[(p[5]+1):p[6], ]
V4 <- r$V[(p[7]+1):p[8], ]
vocab.words1 <- paste0("(es)", r$vocab.words[[1]])
vocab.words2 <- paste0("(de)", r$vocab.words[[2]])
vocab.words3 <- paste0("(fr)", r$vocab.words[[3]])
vocab.words4 <- paste0("(en)", r$vocab.words[[4]])

V <- rbind(V1, V2, V3, V4)
vocab.words <- c(vocab.words1, vocab.words2, vocab.words3, vocab.words4)
```

## Example of vector representation
```{r}
row.sample <- c(p[1], p[2:9]+1)
r$V[row.sample, 1:20]
```

## biplot
```{r}
queries <- c(paste0("(en)", c("i", "you", "he", "she", "my", "your", "her", "we")),
             paste0("(es)", c("yo", "tu", "él", "ella", "mi", "su", "nosotros")),
             paste0("(de)", c("ich", "du", "er", "sie", "mein", "ihr", "sie", "wir")),
             paste0("(fr)", c("je", "tu", "il", "elle", "mon", "votre", "son", "nous")))
n.queries <- length(queries)

print(queries[queries %in% vocab.words])

VV <- V
row.names(VV) <- vocab.words
pr.v2 <- prcomp(VV[queries[queries %in% vocab.words],])
plot(pr.v2$x[ , 1:2], pch = 1, col = "grey")
text(pr.v2$x[ , 1], pr.v2$x[ , 2], row.names(pr.v2$x))
```


```{r}
n.queries.eachlang <- 20
queries <- c(vocab.words1[seq(n.queries.eachlang)],
             vocab.words2[seq(n.queries.eachlang)],
             vocab.words3[seq(n.queries.eachlang)],
             vocab.words4[seq(n.queries.eachlang)])

VV <- V
row.names(VV) <- vocab.words
pr.v2 <- prcomp(VV[queries[queries %in% vocab.words],])
plot(pr.v2$x[ , 1:2], pch = 1, col = "grey")
text(pr.v2$x[ , 1], pr.v2$x[ , 2], row.names(pr.v2$x), cex = 0.7)
```

# Example of lexical translation task
(en)I = (es)yo

```{r}
MostSimilar(V, vocab.words, positive=c("(en)we"), distance = "cosine")
MostSimilar(V, vocab.words, positive=c("(es)yo"), distance = "cosine")
MostSimilar(V, vocab.words, positive=c("(en)france"), distance = "cosine")
MostSimilar(V, vocab.words, positive=c("(en)him", "(es)yo"), negative=c("(en)he"), distance = "cosine")
```

# Execute some (monolingual) tasks for vector representation of english words
```{r}
V.en <- r$V[(p[7]+1):p[8], ]
vocab.en <- r$vocab.words[[4]]

TestGoogleTasks(V.en, vocab.en, n.cores = 12)
TestWordsim353(V.en, vocab.en)
```

# Run time
```{r}
Sys.time() - time.begin
Sys.time()
```