---
title: "Experiment of Eigendocs"
author: "OSHIKIRI Takamasa"
date: "`r Sys.time()`"
output: html_document
---

```{r}
time.begin <- Sys.time()
set.seed(0)

source("./../src/kadingir.R", chdir = TRUE)


## Tuning parameters
n.vocabulary <- 10000 # 語彙に含める単語数
dim.internal <- 50   # 共通空間の次元
window.size <- 2      # 前後何個の単語をcontextとするか
path.corpus <- "./../data/reuters/reuters_rcv1_text.100000.csv"


res.eigendocs <- Eigendocs(path.corpus, n.vocabulary, dim.internal, window.size, plot = TRUE)
save(res.eigendocs, file = "res_eigendocs.Rdata")

## Check vector representations of documents
document.id <- 999
infos <- read.csv("./../data/reuters/reuters_rcv1_infos.100000.csv")

pp <- res.eigendocs$p_head_domains
p <- res.eigendocs$p

word_vectors <- res.eigendocs$V[(pp[1]+1):pp[2], ]
document_vectors <- res.eigendocs$V[(pp[3]+1):p, ]

MostSimilarDocs(document.id, document_vectors, titles = infos$title)
```

```{r}
## Check vector representations of words
MostSimilar(word_vectors, res.eigendocs$vocab.words,
            positive=c("man"), distance = "cosine")
MostSimilar(word_vectors, res.eigendocs$vocab.words,
            positive=c("king", "woman"), negative=c("man"), distance = "cosine")

## Test some tasks for check
TestGoogleTasks(word_vectors, res.eigendocs$vocab.words, n.cores = 24)
TestWordsim353(word_vectors, res.eigendocs$vocab.words)
```

```{r}
Sys.time() - time.begin
Sys.time()
```
