---
title: "Test codes of matrices"
date: "`r Sys.time()`"
output: html_document
---

Check matrices generated by `EigenwordsCpp`, `EigendocsCpp`, `CLEigenwordsCpp`.

```{r}
library(Matrix)

source("./../src/kadingir.R", chdir = TRUE)

word_id <- sample(0:6, size = 100, replace = TRUE)
document_id <- rep(0:9, each = 10)
n <- length(word_id)
window.size <- 2
n.vocab <- length(unique(word_id))
dim.common <- 20

check.identical <- function(a, b) {
  if (all(a == b)) {
    print("passed.")
  } else {
    stop("Two matrices are not identical.")
  }
}
```

```{r}
make.matrices <- function(sentence, document.id, window.size) {

  sentence <- sentence + 1L  # To make min(sentence) == 1 for R indexing
  document.id <- document.id + 1L  # To make min(document.id) == 1 for R indexing
  
  n.train.words <- length(sentence)
  n.vocab <- max(sentence)
  
  ## Construction of W
  indices <- cbind(seq(sentence), sentence, document.id)

  W <- sparseMatrix(i = indices[ , 1], j = indices[ , 2],
                    x = rep(1, times = nrow(indices)),
                    dims = c(n.train.words, n.vocab))

  D.triplet <- cbind(indices[ , 1], indices[ , 3], rep(1, times = nrow(indices)))
  D.triplet <- D.triplet[D.triplet[ , 2] >= 1, ]
  D <- sparseMatrix(i = D.triplet[ , 1], j = D.triplet[ , 2],
                    x = D.triplet[ , 3],
                    dims = c(n.train.words, max(document.id)))
  
  ## Construction of C
  offsets <- c(-window.size:-1, 1:window.size)
  C <- Matrix(F, nrow = n.train.words, ncol = 0)

  for (i.offset in seq(offsets)) {
    offset <- offsets[i.offset]
    indices.temp <- cbind(seq(sentence) - offset, sentence)

    # Ignore invalid indices and indices of null words
    indices.temp <- indices.temp[(indices.temp[ , 1] > 0) & (indices.temp[ , 1] <= n.train.words), ]

    C.temp <- sparseMatrix(i = indices.temp[, 1], j = indices.temp[, 2],
                           x = rep(1, times = nrow(indices.temp)),
                           dims = c(n.train.words, n.vocab))
    C <- cbind2(C, C.temp)
  }

  return(list(W = W, C = C, D = D))
}
```

# Test of `EigenwordsCpp`
```{r}
m <- make.matrices(word_id, document_id, window.size)
res.eigenwords <- EigenwordsOSCCACpp(as.integer(word_id), window.size, n.vocab, dim.common, debug = TRUE)
```

```{r}
matrix.norm2 <- function(a, b) { sum((a - b)**2) }

check.identical(res.eigenwords$tWW_diag, diag(t(m$W) %*% m$W))
check.identical(res.eigenwords$tCC_diag, diag(t(m$C) %*% m$C))
check.identical(res.eigenwords$tWC,      t(m$W) %*% m$C)
```


# Test of `EigendocsCpp`
```{r}
res.eigendocs <- EigendocsCpp(as.integer(word_id), as.integer(document_id),
                              window.size, n.vocab, dim.common, TRUE, TRUE,
                              debug = TRUE)
G.diag.rcpp <- res.eigendocs$G_diag
H.rcpp <- res.eigendocs$H

X <- bdiag(m$W, m$C, m$D)
identity.n <- Diagonal(n)  # nxn-identity matrix
zero.n <- Matrix(0, nrow = n, ncol = n)  # nxn-zero matrix
W <- rBind(cBind(zero.n, identity.n, identity.n),
           cBind(identity.n, zero.n, identity.n),
           cBind(identity.n, identity.n, zero.n))
M <- diag(rowSums(W))
G.diag.r <- diag(t(X) %*% M %*% X)
H.r <- triu(t(X) %*% W %*% X)

check.identical(G.diag.rcpp, G.diag.r)
check.identical(H.rcpp, H.r)
```


# Test of `CLEigenwordsCpp`
```{r}
n.vocab <- c(7, 9)
n.token <- c(40, 60)
word.id.1 <- sample(seq(n.vocab[1]) - 1, size = n.token[1], replace = TRUE)
word.id.2 <- sample(seq(n.vocab[2]) - 1, size = n.token[2], replace = TRUE)
word.id.concated <- c(word.id.1, word.id.2)
document.id.1 <- rep(-2:1, each = 10)
document.id.2 <- rep(-1:4, each = 10)
document.id.concated <- c(document.id.1, document.id.2)
weight.vsdoc <- c(2, 1)

results.cleigenwords <- CLEigenwordsCpp(word.id.concated, document.id.concated,
                                        window.size * c(1, 1),
                                        n.vocab * c(1, 1),
                                        n.token * c(1, 1),
                                        dim.common, 2*dim.common+10,
                                        link_v_c = TRUE,
                                        weight_vsdoc = weight.vsdoc,
                                        debug = TRUE)
G.diag.rcpp <- results.cleigenwords$G_diag
H.rcpp <- results.cleigenwords$H

n1 <- length(word.id.1)
n2 <- length(word.id.2)
n.documents <- max(document.id.concated) + 1
m1 <- make.matrices(word.id.1, document.id.1, window.size)
m2 <- make.matrices(word.id.2, document.id.2, window.size)

identity.n1 <- Diagonal(n1)
identity.n2 <- Diagonal(n2)
zeros <- function(n1, n2) { Matrix(0, nrow = n1, ncol = n2) }

J1.triplet <- cbind(seq(n1), document.id.1 + 1, rep(1, n1))
J1.triplet <- J1.triplet[J1.triplet[ , 2] >= 1, ]
J1 <- sparseMatrix(i = J1.triplet[ , 1], j = J1.triplet[ , 2], x = J1.triplet[ , 3], dims = c(n1, n.documents))
J1 <- weight.vsdoc[1] * J1

J2.triplet <- cbind(seq(n2), document.id.2 + 1, rep(1, n2))
J2.triplet <- J2.triplet[J2.triplet[ , 2] >= 1, ]
J2 <- sparseMatrix(i = J2.triplet[ , 1], j = J2.triplet[ , 2], x = J2.triplet[ , 3], dims = c(n2, n.documents))
J2 <- weight.vsdoc[2] * J2
W <- rBind(cBind(zeros(n1, n1), identity.n1,   zeros(n1, n2), zeros(n1, n2), J1),
           cBind(identity.n1,   zeros(n1, n1), zeros(n1, n2), zeros(n1, n2), J1),
           cBind(zeros(n2, n1), zeros(n2, n1), zeros(n2, n2), identity.n2,   J2),
           cBind(zeros(n2, n1), zeros(n2, n1), identity.n2,   zeros(n2, n2), J2),
           cBind(t(J1),         t(J1),         t(J2),         t(J2),         zeros(n.documents, n.documents)))
D <- Diagonal(n.documents)
X <- bdiag(m1$W, m1$C, m2$W, m2$C, D)

M <- diag(rowSums(W))
G.diag.r <- diag(t(X) %*% M %*% X)
H.r <- triu(t(X) %*% W %*% X)

check.identical(G.diag.rcpp, G.diag.r)
check.identical(H.rcpp, H.r)
```